name: currency_rate_bot
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - html5lib=1.1
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - libcxx=12.0.0
  - libffi=3.3
  - libsodium=1.0.18
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - numexpr=2.8.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.1.2
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - pytz=2022.1
  - pyzmq=23.2.0
  - readline=8.1.2
  - requests=2.28.1
  - selenium=3.141.0
  - send2trash=1.8.0
  - setuptools=61.2.0
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
